name: Test Handler
on:
  pull_request:
    branches: [ master, main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Test
        run: |
          cd handler
          go test -v -covermode=atomic -coverprofile=coverage.out