name: Upload release

on:
  release:
    types: [published]

jobs:
  upload:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.0'
      - name: Build function
        run: make function
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          asset_path: ./function.zip
          asset_name: function.zip
          asset_content_type: application/zip
          upload_url: ${{ github.event.release.upload_url }}